### ISSUE TITLE
Discuss office hours - schedule next actions

### ISSUE THREAD

**Issue by mellieA** [grafana/grafana-community-support-squad#39]

**Comment by mellieA** [comment]
@natellium which squads do you think  we could visit next? 

So far we've met with 

- Alerting
- User essentials
- Backend

**Comment by natellium** [comment]
I'd suggest observability experience for anything Explore or GLUE? Do we have some things for them? I think they'd be a cool squad to meet up, also part of Platform UX

**Comment by mellieA** [comment]
Ooooh! Explore! We have lots for them
