### ISSUE TITLE
Tooling: ping internal issue creators to label their issues when it has none

### ISSUE THREAD

**Issue by natellium** [grafana/grafana-community-support-squad#43]
### What
Ping Grafanistas when they create an issue with no labels. This would help educating them on how to create GH issues + help reducing the amount of issues in triage. 

### Resources
We currently have a label that gets added when a PR is created by someone from outside the org. We should be able to reuse some of its logic.
* Command definition: https://github.com/grafana/grafana-github-actions/blob/main/commands/Commands.js#L55
* Command usage in grafana repo https://github.com/grafana/grafana/blob/main/.github/pr-commands.json#L187
* Command config in grafana repo https://github.com/grafana/grafana/blob/main/.github/workflows/pr-commands.yml

**Comment by zuchka** [comment]
looks like commands.js is using this:

https://octokit.github.io/rest.js/v19#orgs-check-membership
which is a wrapper for this:
https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user

we could probably just use the `memberOf` check the same way the external PRs action in our repo uses the `notMemberOf` check.

so like:
```
  {
    "type": "author",
    "name": "issue/internal",
    "memberOf": { "org": "grafana" },
    "ignoreList": ["renovate[bot]","dependabot[bot]"],
    "action": "pingGrafanista",
    "addLabel": "needs-more-info"
  }
```

we’d just have to write the logic for the pingGrafanista part :rocket:
